### ISSUE TITLE
Android gradle package manager support

### ISSUE THREAD

**Issue by black-snow** [KeepSafe/Switchboard#20]
It would be great if I just had to `compile 'com.keepsafe:switchboard:1.2.3'` in my android project.

**Comment by philippb** [comment]
I agree. It's on my mind and I want to do ti and extend the client with some extra functionality.

Do you use Switchboard in production?

**Comment by black-snow** [comment]
I'm not yet using it. I wanted to give it a try but gave some other tasks priority for there was no package on maven / jcenter. Will probably give it a shot in the last couple weeks.
Cheers

**Comment by raulccabreu** [comment]
@black-snow, we are using Switchboard on our projects, and making some changes on our fork Catbag/Switchboard. This issue for example are accomplished on our fork. We opened a PR for gradle build implementation, when the opened PR get merged we follow with anothers to achieve this on KeepSafe upstream

use ```compile 'br.com.catbag.switchboard:android-client:1.0.0'```

change your root build.gradle repositories to add https://dl.bintray.com/catbag/maven repo
```
allprojects {
    repositories {
        jcenter()
        maven {
            url  "https://dl.bintray.com/catbag/maven"
        }
    }
}
```
